### ISSUE TITLE
Missing linux release package for v0.1.18

### ISSUE THREAD

**Issue by jamezrin** [httptoolkit/httptoolkit-desktop#14]
Hello, I maintain the AUR package [`httptoolkit-bin`](https://aur.archlinux.org/packages/httptoolkit-bin) as well as [`httptoolkit`](https://aur.archlinux.org/packages/httptoolkit) (which builds from source).

The first package relies on the `deb` package file, and in the latest GitHub release it is not present. 
Do you know why this might be? Thank you.

**Comment by pimterry** [comment]
Hi @jamezrin, yes, there seems to have been a hiccup in the script deploying to github, where the Linux files refused to upload.

In the end I've dropped all 0.1.18 release files, and triggered a rebuild of the whole thing, which seems to have worked fine now. All 0.1.18 assets are now available.

I didn't realise you were closely subscribing to release publishes in this repo though. It's slightly risky to do so - releases are always published here, but I then typically do a final manual per-platform test afterwards, before updating the release used as the official httptoolkit.tech download here: https://github.com/httptoolkit/httptoolkit.tech/blob/master/gatsby-node.js#L6. It's completely possible that a bad release could appear briefly and then be removed afterwards.

If that's not a huge concern then it's ok, but it might be better if you subscribed directly through the website somehow. How does your script check for changes? It would be very easy for me to host a file at httptoolkit.tech/LATEST_VERSION containing name of the latest officially released version - would that be useful?

**Comment by jamezrin** [comment]
Hi, it's not a script, I do the updates manually as soon as I see a new release in this repo. I always launch the app to see if it works and try intercepting chrome, if that works I push the update to the AUR.

For the next updates I will take a look at the website to see if it was released there, but something to know when the website has a new release would be good. That endpoint you suggested should be enough, I can set up a script that lets me know if it changed.

**Comment by pimterry** [comment]
Ok great, done: https://httptoolkit.tech/latest-version.

That data comes from the same config as the version used for the download link, so it'll always be the current officially recommended version.

I'll close this now, but do let me know if anything else like this pops up in future.
