### ISSUE TITLE
httptoolkit-desktop refuses to run via start:dev in Windows 10

### ISSUE THREAD

**Issue by rSh4d0w** [httptoolkit/httptoolkit-desktop#19]
i cloned the httptoolkit-ui, httptoolkit-server and httptoolkit-desktop repo.
the first two run fine, however the desktop app refuses to run started via start:dev.
i use the node.js command prompt, and start via "npm run start:dev".
![1](https://user-images.githubusercontent.com/20821454/93636676-a263b000-f9f4-11ea-8199-69b8265d48c1.PNG)
even if i remove the shebang line "`#!/usr/bin/env node
setInterval(() => {}, 999999999);
`;" and turn it into "`node
setInterval(() => {}, 999999999);
`;" and make sure the httptoolkit-server.cmd contains the same, it crashes again, complaining about not knowing the setInterval command.
![2](https://user-images.githubusercontent.com/20821454/93637480-f9b65000-f9f5-11ea-83a6-e4f4bd5cdfa4.PNG)
if i run the command myself in the command prompt it works fine, it only fails if the start script/desktop app does it.

**Comment by pimterry** [comment]
@rSh4d0w can you provide any details on how you fixed this? I'm sure it'd be useful to other people doing the same thing!

**Comment by rSh4d0w** [comment]
Sure! 
setup-dev.js
![grafik](https://user-images.githubusercontent.com/20821454/93906211-376bef00-fcfc-11ea-8bb0-79d1e2ad9d93.png)
doesn't work under Win. Windows complains about the shebang, after removal node complains about not finding the module "setInterval".
i edited this part into
![grafik](https://user-images.githubusercontent.com/20821454/93906475-86198900-fcfc-11ea-9a46-14143a15e1c9.png)
and created a file called run.js
with "setInterval(() => {}, 999999999);" inside.
script should be placed in the root folder of httptoolkit-desktop.
not the cleanest solution, but got the job quickly done, to run the program.
