### ISSUE TITLE
app crashes

### ISSUE THREAD

**Issue by Githubus3r3** [httptoolkit/httptoolkit-desktop#47]
the http toolkit app on windows 11 keeps on crashing for me every time i try to start it. 
![HTTP_Toolkit_vfSjbhtXXN](https://user-images.githubusercontent.com/114313670/192117867-43d1c728-aa63-46aa-a1ea-a668c62bd761.png)

**Comment by akari-dogman** [comment]
Had this same problem, looked at the closed issues and found this fix that worked for me:
> This was due to a server update that seems to have had some issues on Windows, sorry about that!
> 
> I've now rolled back the release, I think that should resolve this, but if you've updated already and you're still hitting this error, you can delete the server update directory (`C:\Users\<username>\AppData\Local\httptoolkit-server`) to revert that.

https://github.com/httptoolkit/httptoolkit/issues/337#issuecomment-1256941021

**Comment by pimterry** [comment]
Exactly, thanks @akari-dogman!
