### ISSUE TITLE
HTML markup showing up in the Debian installer

### ISSUE THREAD

**Issue by digitalsanctum** [httptoolkit/httptoolkit-desktop#58]
I noticed there's HTML markup showing in the title for the Debian installer.

![httptoolkit-issue](https://user-images.githubusercontent.com/30923/232047648-7dc3106f-661e-48c9-a254-0ddfc6688a77.png)

**Comment by pimterry** [comment]
I did some more digging, I actually have no idea where this is coming from. I've extracted the contents of the latest package manually with `dpkg-deb -R <pkg> .` and examining the metadata shows:

```
Package: httptoolkit
Version: 1.12.6
License: AGPL-3.0-or-later
Vendor: contact@httptoolkit.tech
Architecture: amd64
Maintainer: contact@httptoolkit.tech
Installed-Size: 375997
Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libsecret-1-0
Recommends: libappindicator3-1
Section: default
Priority: optional
Homepage: https://httptoolkit.tech
Description: 
  HTTP(S) debugging, development & testing tool
```

So the `<b>...</b>` isn't actually present at all. I've also opened the package with gdebi, and it appears correctly there with no problems - this only appears with Eddy (which I've just installed specifically to reproduce this). Is it possible that Eddy is adding this somewhere for some reason? Do you see this with other packages? I don't know much about Eddy at all.

**Comment by digitalsanctum** [comment]
I haven't seen the issue otherwise but I'm also told I'm not observant 😀 

I took a quick look on eddy and PopOS repos to see if it's been reported but didn't find anything.

**Comment by pimterry** [comment]
Ok, I'll file an issue with Eddy and see if they know what's up here.
