### ISSUE TITLE
Hi, can you add dark mode please? Everything is way too bright. Thanks.

### ISSUE THREAD

**Issue by Michael-Github-2023** [httptoolkit/httptoolkit-desktop#63]
Hi, can you add dark mode please? Everything is way too bright. Thanks.

**Comment by pimterry** [comment]
Hi @Michael-Github-2023 :smile:. This is a duplicate of https://github.com/httptoolkit/httptoolkit/issues/183 - I'll close this issue, but do take a look at the comments there for some context.
