### ISSUE TITLE
Publish standalone native Apple Silicon binaries for macOS

### ISSUE THREAD

**Issue by 1366613** [httptoolkit/httptoolkit-desktop#64]

**Comment by pimterry** [comment]
You've previously created the exact same issue in this same repo (#59) which was already closed - this is a duplicate of https://github.com/httptoolkit/httptoolkit/issues/371.

There hasn't been any progress here recently (although the new GitHub M1 runners should help a lot!) but PRs are very welcome if you want to help make this happen.
