### ISSUE TITLE
1.14.11 a beta version

### ISSUE THREAD

**Issue by core-code** [httptoolkit/httptoolkit-desktop#68]
is 1.14.11 a beta version?

1.14.10 is still marked as "latest"

<img width="150" alt="Screenshot 2024-04-12 at 22 38 01" src="https://github.com/httptoolkit/httptoolkit-desktop/assets/1261954/8d98e986-2df2-43c1-b07c-3ec37697ea47">

**Comment by pimterry** [comment]
Oh, no that's just a mistake. Now fixed :smile:. Thanks for reporting this!
