### ISSUE TITLE
Why Global chrome Not opening ?

### ISSUE THREAD

**Issue by RDXSquad** [httptoolkit/httptoolkit-desktop#78]
Browser cache updated
Error handling request to /interceptors/existing-chrome/activate/8000: spawn wmic ENOENT
ERROR: 500 [object Object]
INFO: Reporting error: Error: Failed to activate interceptor existing-chrome: spawn wmic ENOENT [object Object]
INFO: Previous server version was null
Error handling request to /interceptors/existing-chrome/activate/8000: spawn wmic ENOENT
Error: spawn wmic ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn wmic',
  path: 'wmic',
  spawnargs: [ 'Process', 'Get', 'processid,commandline' ]
}
ERROR: 500 [object Object]
INFO: Reporting error: Error: Failed to activate interceptor existing-chrome: spawn wmic ENOENT [object Object]

How to Solve this issuse

**Comment by pimterry** [comment]
That looks like you don't want `wmic` installed, which is quite unusual, I think that's standard on Windows. What OS version exactly are you using? Are you an administrator on the machine?

**Comment by pimterry** [comment]
Ah, it looks like WMIC is being removed in Windows 11 this year. As a workaround, can you try the steps here? https://techcommunity.microsoft.com/blog/windows-itpro-blog/how-to-install-wmic-feature-on-demand-on-windows-11/4189530

Let me know if that works. I will look into updating to support the new approaches required here soon.

**Comment by pimterry** [comment]
This is now fixed in the latest HTTP Toolkit. If you open the app, it'll update in the background within a minute or so, and the following launch everything should work correctly. Thanks for reporting this, do let me know if you find any more issues in future!
