### ISSUE TITLE
No UI is shown on Linux

### ISSUE THREAD

**Issue by dessant** [httptoolkit/httptoolkit-desktop#8]
I've tried to test HTTP.Toolkit-linux-x64-0.1.14.zip on Arch Linux, but when `httptoolkit` is launched from the command line, only an empty Electron window is shown.

```shell
$ ./httptoolkit 
Config checked in 2 ms
Certificates setup in 3 ms
Server started in 22 ms
Total startup took 28 ms
```

![Screenshot from 2019-09-26 10-26-50](https://user-images.githubusercontent.com/7513068/65667454-6cd9f000-e048-11e9-9d6b-37e04f3d9570.png)

**Comment by jamezrin** [comment]
The deb package works fine, there is an AUR package for it https://aur.archlinux.org/packages/httptoolkit

**Comment by pimterry** [comment]
Yep, that's not supposed to happen. Not sure what's going on here since the two packages should be identical, I'll take a look today.

**Comment by jamezrin** [comment]
I think the package is fine, I tried to reproduce it and the zip package worked just fine.
![image](https://user-images.githubusercontent.com/5949554/65679300-17581000-e055-11e9-9e66-7f2d64787f58.png)

**Comment by pimterry** [comment]
I've given it a test myself, and I can't reproduce this either @dessant.

The UI loads initially on the first start from the network (the hosted UI lives at `https://app.httptoolkit.tech`). After that, it runs from a service worker, so it works offline and loads quickly, but for the first run it needs to be able to load the page. Is there some reason that might not work on your machine?

You can also check the developer console in the app, which might have some tips. You can access it from the menu: go to View -> Toggle Developer Tools -> Console, and let me know if there are any errors that appear there.

**Comment by dessant** [comment]
I have ran it twice and got the same result, but now it loads instantly, despite the offline cache having been cleared. At the time the project was trending on HN, so maybe it was a network error. Sorry for the false alarm. :yum:

**Comment by pimterry** [comment]
Ok, great to hear, thanks for letting me know!
