### ISSUE TITLE
Move from Electron Forge to Electron Builder

### ISSUE THREAD

**Issue by pimterry** [httptoolkit/httptoolkit-desktop#9]
Forge v5 is not really supported, Forge v6 is still very early, and Builder seems by far the more popular & well supported version for the future. Updating would set us up much better for future plans, and let us immediately update Electron etc, which would likely fix a few small bugs and let us bring back the Windows standalone build (currently broken)

**Comment by jamezrin** [comment]
Hey! You already did this :)

**Comment by pimterry** [comment]
Good catch! You're totally right, thanks for the reminder :smiley:
